### ISSUE TITLE
How to plot Fig5 in paper? what toolkit?

### ISSUE THREAD

**Issue by laisimiao** [SkyeSong38/CSWinTT#2]

**Comment by SkyeSong38** [comment]
I resized the attention score to the same size as the original image, drew it using the python tool **matplotlab**, then imported the score map and the original image into **PPT**, set the transparency and overlaid them.

**Comment by tommycwh** [comment]
May I ask where do you get the attention scores? Do you use the attention scores that are retrieved here?
https://github.com/SkyeSong38/CSWinTT/blob/27b78f9b0b1eebecfd5b3d3dbdc591c6562e69d7/lib/models/cswintt/transformer_cs.py#L288
